### ISSUE TITLE
NodeDataModel __init__ called twice when adding node in flow_scene

### ISSUE THREAD

**Issue by Picard2200** [klauer/qtpynodeeditor#42] opened 2020-08-26 14:10 UTC
It seems that in flow_view.py (click_handler), the __init__ is called once in self._scene.registry.create(model_name) and another time in self._scene.create_node(type_)

## Expected Behavior

NodeDataModel __init__ method should be called only once per node when using the GUI for adding a node.
Note: this issue does not occur when the node is added directly in the Python script as it is done in calculator.py.

self._scene.registry.create(model_name) (line 168 of flow_view.py) should check whether a model exists already without having to create an instance.
If the model does exist, icreate an instance of that model thru the call to self._scene.create_node(type_) (line 170 from flow_view.py)

## Current Behavior

self._scene.registry.create(model_name) creates an instance of the class "model_name" (hence calling __init__) and call __init__ again in self._scene.create_node(type_)
This occurs only when click_handler (line 163 of flow_view.py) is called

Calling __init__ only once ensures that what is done inside the __init__ will be done once.
## Possible Solution

If a model has been created already, do not create it again, what could be done by having a way to check whether a model has been created already

## Steps to Reproduce (for bugs)

I have added a print('NumberSourceDataModel') in the __init__ of NumberSourceDataModel in calculator.py (provided as an example by qtpynodeeditor).
When I run calculator.py, this message is printed 10 times as expected (5 * 2)
But when I add a NumberSourceDataModel from the screen, I have 2 print for a single instance, what I find not normal.

1.
2.
3.

## Context

I have a NodeDataModel for Webcam acquisition using opencv.VideoCapture. This call is very long already but when called twice it is even worst. 

## Your Environment

python 3, pyqt5, last qtpynodeeditor version installed in July

**Comment by klauer** [comment] 2020-08-27 16:10
Hmm, that's not good at all. Thanks for reporting - I'll try to take a look into this soon.

**Comment by Daguerreo** [comment] 2020-08-27 16:15
> Hmm, that's not good at all. Thanks for reporting - I'll try to take a look into this soon.

This happens in C++ version too, so it's not a problem of the porting.

**Comment by klauer** [comment] 2020-08-27 16:22
That's good to know, @Daguerreo - thanks.

**Comment by Daguerreo** [comment] 2020-08-27 16:26
I have to investigate better, but at first glance FlowScene::nodeDoubleClicked too seems to be called twice. They could be related

**Comment by klauer** [comment] 2020-09-04 16:12
Reopening - @Picard2200 noted that he's still seeing the issue in v0.2.0 in #44.

@Picard2200, are you 100% sure you're running the latest version? And also that you're not running the example from, say, an older qtpynodeeditor git repository root? Python can do funny things related to library paths depending on where you run things from. 

If you could, please create a new environment and outline the steps you use on the command-line to reproduce it.

**Comment by Picard2200** [comment] 2020-09-04 18:06
No, I am not 100% sure. I am pretty confident that I took the last version but I will double check:
Do you have a way to determine the installed version ? (sorry I am not in front of my Pc right now)

**Comment by klauer** [comment] 2020-09-04 18:11
I unfortunately messed up the version information - and am intending to fix that in #47 (such that you'll be able to do `python -c 'import qtpynodeeditor; print(qtpynodeeditor.__version__)'`).

You could see at least where it's being imported from by doing `python -c 'import qtpynodeeditor; print(qtpynodeeditor.__file__)`. And assuming that's coming from your conda environment site-packages, then double-checking with `conda list |grep qtpynodeeditor` should do it.

**Comment by Picard2200** [comment] 2020-09-04 19:26
I took the zip from here: https://github.com/klauer/qtpynodeeditor
I have run "python setup.py install" on this version.
I have checked that it is installed in my conda env: C:\ProgramData\Miniconda3\lib\site-packages
But I have still "MathOperations" printed twice after having print in the associated __init__ method

So I will wait for your version that allows to print __version__

Thank you again for your support

**Comment by Picard2200** [comment] 2020-09-07 06:29
Hi Klauer, Just to let you know that I tried to install qtpynodeeditor using the install command for conda using pip and I just got an egg, no installation at all. So may be this is why I do not see your fix: it is may be not installed properly.

**Comment by klauer** [comment] 2020-09-08 15:53
Strange, @Picard2200 - here are my results:

```
$ conda create -n temp2 python=3.7 qtpynodeeditor pyqt 
# (qtpynodeeditor-0.2.0       |             py_0          40 KB  conda-forge)

$ conda activate temp2
$ cp $CONDA_PREFIX/lib/python3.7/site-packages/qtpynodeeditor/examples/calculator.py .
$ vim calculator.py   # add debug message to MathOperation.__init__
$ python calculator.py
...
(click "addition")
Math operation! <__main__.AdditionModel object at 0x7fc03760a910>
```

Only a single output...

Attempt 2:

```
$ conda create -n temp3 python=3.7 pyqt qtpy
$ conda activate temp3
$ pip install qtpynodeeditor  
# (finds qtpynodeeditor-0.2.0.tar.gz)
$ python calculator.py
...
(click "addition")
Math operation! <__main__.AdditionModel object at 0x7f8761801a50>
```

And the same

**Comment by Picard2200** [comment] 2020-09-11 11:39
Hi Klauer,

I have reinstalled my whole conda environment and I am happy to tell you that your fix works perfectly.
Bug fixed!

Thank you for your responsiveness and for your support on my issues to install the fix

**Comment by klauer** [comment] 2020-09-11 16:16
👏 Glad to hear it, @Picard2200! Closing this issue for good.

**Closed by klauer** 2020-09-11 16:16 UTC

**Comment by Daguerreo** [comment] 2020-09-14 15:12
@klauer  just out of curiosity, maybe you could confirm come from the C++ version?

**Comment by klauer** [comment] 2020-09-14 16:24
@Daguerreo it doesn't appear to be the same issue, interestingly enough:

The culprit in qtpynodeeditor - `create()` returning an instance instead of the node factory itself isn't present in the upstream nodeeditor:
https://github.com/paceholder/nodeeditor/blob/a939cf865933d797483694f797e06e1f1c8cdb27/src/FlowView.cpp#L163

https://github.com/paceholder/nodeeditor/blob/a939cf865933d797483694f797e06e1f1c8cdb27/src/FlowScene.cpp#L195-L209

Seems like it'd be a good idea to just drop into a debugger to see where it's happening in the C++ version - it's been a while since I delved into its code.

Is this perhaps related to your `nodeCreated` signal emitted twice issue, @Daguerreo? (https://github.com/paceholder/nodeeditor/issues/270) If so, this may have been two separate issues that ended up looking similar - init called twice vs signal emitted twice.

**Comment by Daguerreo** [comment] 2020-09-15 06:23
@klauer thank you for the reply. Yes it was. I'm suspecting that bug (and maybe this one too), has another side effect: checking with valgrind embedded widgets area leaking memory systematically, yet widget is destroyed from the QGraphicsProxyWidget. So maybe the double create call lead the creation of 2 embedded widgets, where the is the first created which is actually leaking. Still investigating though.
